config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reviews
  resources :designs
  resources :companies

  root to: 'static#home'
  get 'home' => 'static#home'

  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  get    '/users/sign_in'  => 'devise/sessions#new'
  get '/users/password/new' => 'devise/passwords#new'

end

  get 'companies/:id' => 'companies#show'
  get 'companies/:id' => 'designs#create'
  get 'companies/new' => 'companies#create'
  get 'companies/:id/edit' => 'companies#edit'
  get 'companies' => 'companies#index'

  get 'designs/:id' => 'designs#show'
  get 'designs' => 'designs#index'
  get 'designs/new' => 'designs#create'

  get 'reviews' => 'reviews#index'
  get 'reviews/new' => 'reviews#create'
  get 'reviews/:id' => 'reviews#show'

end

app/models/design.rb
class Design < ActiveRecord::Base
  has_many :reviews
  belongs_to :company
  has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :set_design, only: [:show, :edit, :update, :destroy]
  # if current user is a reviewer then they will be redirected to the companies page when visiting those pages
  before_action :is_reviewer, only: [:create, :edit, :update, :destroy]

  # GET /designs
  # GET /designs.json
  def index
    @designs = Design.all
  end


  # GET /designs/1
  # GET /designs/1.json
  def show
  end

  #if not a company redirect to the path, COMMENT OUT THE LINE WHEN WEBSITE WORKING
    def is_reviewer
      if !current_user.company?
        #redirect_to companies_path
      end
    end


  # GET /designs/new
  def new
    @design = Design.new
  end

  # GET /designs/1/edit
  def edit
  end

  # POST /designs
  # POST /designs.json
  def create
    @design = Design.new(design_params)

    respond_to do |format|
      if @design.save
        format.html { redirect_to @design, notice: 'Design was successfully created.' }
        format.json { render :show, status: :created, location: @design }
      else
        format.html { render :new }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designs/1
  # PATCH/PUT /designs/1.json
  def update
    respond_to do |format|
      if @design.update(design_params)
        format.html { redirect_to @design, notice: 'Design was successfully updated.' }
        format.json { render :show, status: :ok, location: @design }
      else
        format.html { render :edit }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designs/1
  # DELETE /designs/1.json
  def destroy
    @design.destroy
    respond_to do |format|
      format.html { redirect_to designs_url, notice: 'Design was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_design
      @design = Design.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def design_params
      params.require(:design).permit(:product_name, :description, :image)
    end
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/views/designs/_form.html.erb
<%= form_for @design, html: { multipart: true } do |f| %>
  <% if @design.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@design.errors.count, "error") %> prohibited this design from being saved:</h2>

      <ul>
      <% @design.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
   <%= f.label :image %><br>
   <%= f.file_field :image %>
 </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/designs/edit.html.erb
<h1>Editing Design</h1>

<%= render 'form' %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

app/views/designs/index.html.erb
<p id="notice"><%= notice %></p>
<div class="design_list">
<h1>Listing Designs</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Product Name</th>
      <th>Description</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @designs.each do |design| %>
      <tr>
        <td><%= image_tag design.image.url(:thumb) %></td>
        <td><%= design.product_name %></td>
        <td><%= design.description %></td>
        <td><button type="button" class="btn btn-primary"><%= link_to 'Show/Review', design %></button></td>
        <!-- for companies eyes only -->
        <%if current_user.company%>
        <td><button type="button" class="btn btn-primary"><%= link_to 'Edit', edit_design_path(design) %></button></td>
        <td><button type="button" class="btn btn-primary"><%= link_to 'Destroy', design, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
        <!-- ending companies eyes only   -->
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.company %>
<%= link_to 'New Design', new_design_path %>
<% end %>
</div>

app/views/designs/new.html.erb
<div class ="design_container">
<h1>New Design</h1>
<%= render 'form' %>

<%= link_to 'Back', designs_path %>
</div>

app/views/designs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="design_show">
<p><%= image_tag @design.image.url(:large) %></p>

<p>
  <strong>Product name:</strong>
  <%= @design.product_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @design.description %>

</p>


<% @design.reviews.each do |reviewz|%>
   <%=reviewz.rating %>
   <%end%>


<!-- for companies eyes only -->
<%if current_user.company%>
<p><%= link_to 'Edit', edit_design_path(@design) %></p>
<p><%= link_to 'Reviews', reviews_path(@reviews) %></p>
<%else%>
<p><%= link_to 'Review Design', reviews_path(@design) %></p>
<p><%= link_to 'Back', designs_path %></p>
<%end%>
</div>