config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reviews
  resources :designs
  resources :companies

  root to: 'static#home'
  get 'home' => 'static#home'

  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  get    '/users/sign_in'  => 'devise/sessions#new'
  get '/users/password/new' => 'devise/passwords#new'

end

  get 'companies/:id' => 'companies#show'
  get 'companies/:id' => 'designs#create'
  get 'companies/new' => 'companies#create'
  get 'companies/:id/edit' => 'companies#edit'
  get 'companies' => 'companies#index'

  get 'designs/:id' => 'designs#show'
  get 'designs' => 'designs#index'
  get 'designs/new' => 'designs#create'

  get 'reviews' => 'reviews#index'
  get 'reviews/new' => 'reviews#create'
  get 'reviews/:id' => 'reviews#show'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :designs
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  # if current user is not a company then they will be redirected on the following pages:
  before_action :is_reviewer, only: [:edit, :update, :destroy]



  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end


#if not a company redirect to the path COMMENT OUT THE MIDDLE LINE WHEN READY TO ADD FEAUTE. IT WORKS, PROMISE
  def is_reviewer
    if !current_user.company?
      # redirect_to companies_path
    end
  end



  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :category)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>
<div class="company_list">
<h1>Listing Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.category %></td>
        <%if !current_user.company %>
        <td><%= link_to 'Show', company %></td>
        <% else %>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%if current_user.company%>
<%= link_to 'New Company', new_company_path %>
<% end %>
</div>

app/views/companies/new.html.erb
<div class="new_company">
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>
</div>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<div class="company_show">
<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @company.category %>
</p>



<% @company.designs.each do |hellohoez|%>
   <%=hellohoez.rating %>
   <%end%>


<%if current_user.company%>
<p id="link"><%= link_to 'New Design', new_design_path %></p>

<p id="link"><%= link_to 'Edit', edit_company_path(@company) %></p>
<%end%>
<p id="link"><%= link_to 'Company Designs', designs_path(@company) %></p>
<p id="link"><%= link_to 'Back', companies_path %></p>
</div>