config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reviews
  resources :designs
  resources :companies

  root to: 'static#home'
  get 'home' => 'static#home'

  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  get    '/users/sign_in'  => 'devise/sessions#new'
  get '/users/password/new' => 'devise/passwords#new'

end

  get 'companies/:id' => 'companies#show'
  get 'companies/:id' => 'designs#create'
  get 'companies/new' => 'companies#create'
  get 'companies/:id/edit' => 'companies#edit'
  get 'companies' => 'companies#index'

  get 'designs/:id' => 'designs#show'
  get 'designs' => 'designs#index'
  get 'designs/new' => 'designs#create'

  get 'reviews' => 'reviews#index'
  get 'reviews/new' => 'reviews#create'
  get 'reviews/:id' => 'reviews#show'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  # if current user is a company they are unable to post, edit, destroy, create a review
  before_action :is_company, only: [:destroy, :create, :update]


  def is_company
    if current_user.company?
      redirect_to reviews_path
    end
  end


  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end



  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:comment, :title, :rating)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
     <%= f.label :rating %><br>
     <%= f.radio_button(:rating, "Like") %>
     <%= label_tag(:rating, "Like") %>
     <%= f.radio_button(:rating, "Indifferent") %>
     <%= label_tag(:rating, "Indifferent") %>
     <%= f.radio_button(:rating, "Dislike") %>
     <%= label_tag(:rating, "Dislike") %>
   </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>
<div class="reviews_list">
<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Title</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.comment %></td>
        <td><%= review.title %></td>
        <td><%= review.rating %></td>
    
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- for reviewers eyes only hoes -->
<%if !current_user.company%>
<%= link_to 'New Review', new_review_path %>
<!-- the end hoe -->
<%end%>
</div>

app/views/reviews/new.html.erb
<div class="reviews_container">
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>
</div>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>
<div class="review_show">
<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<!-- for reviewers eyes only -->
<%if !current_user.company%>
<p><%= link_to 'Edit', edit_review_path(@review) %></p>
<!-- end -->
<%end%>
<p><%= link_to 'Back', reviews_path %></p>
</div>